# Data Science Club Presentation - Pandas

In [3]:
# Import packages
import pandas as pd # Built on the numpy package
import numpy as np

In [2]:
# Create a Pandas Series
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)

x    1
y    7
z    2
dtype: int64


In [4]:
# To access an item in a pandas series
print(myvar[0])
print(myvar["x"])

1
1


In [5]:
# To add a single value
myvar["a"] = 5
myvar

x    1
y    7
z    2
a    5
dtype: int64

In [7]:
# We can combine series by using the append function
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
s3 = s1.append(s2)
s3

0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

In [8]:
s3[0]

0    1
0    4
dtype: int64

In [9]:
s4 = s1 + s2
print(s4)

0    5
1    7
2    9
dtype: int64


## Create Dataframes given different data types

In [11]:
# Create Pandas Dataframe from multiple lists
lst = ['Geeks', 'For', 'Geeks']
lst2 = [11, 22, 33]

df = pd.DataFrame(zip(lst, lst2),
                 columns = ['key', 'value'])
df

key  value
0  Geeks     11
1    For     22
2  Geeks     33

In [31]:
# Same thing
df = pd.DataFrame(list(zip(lst, lst2)),
                 columns = ['key', 'value'])
df

key  value
0  Geeks     11
1    For     22
2  Geeks     33

In [33]:
zip(lst, lst2)

In [32]:
# zip function returns a list of tuples
# [('Geek', 11), ('For', 22), ('Geeks', 33 )]
list(zip(lst, lst2))

[('Geeks', 11), ('For', 22), ('Geeks', 33)]

In [34]:
# Create Pandas Dataframe from a list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns = ['Name', 'Age'])
df

Name  Age
0   tom   10
1  nick   15
2  juli   14

In [13]:
# Create Pandas Dataframe from a list of tuples
data = [('tom', 10), ('nick', 15)]
df = pd.DataFrame(data, columns = ['Name', 'Age'])
df

Name  Age
0   tom   10
1  nick   15

In [16]:
# Create Pandas Dataframe from a dictionary
data = {'Name': ['Tom', 'nick'],
       'Age': [10, 15]}
df = pd.DataFrame(data)
df

Name  Age
0   Tom   10
1  nick   15

In [17]:
print(df) # Not stylish output

   Name  Age
0   Tom   10
1  nick   15


## Open files with Pandas

pd.read_**file format**(filename)

pd.read_csv

pd.read_excel

In [37]:
# pd.read_csv to open a comma separated value (CSV) file
# pd.read_csv with param sep or delimiter set as '\t' to open tab separated value (TSV) file 
# https://sparkbyexamples.com/pandas/pandas-read-tsv-into-dataframe/
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePathOrBuffer', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=False, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_me

In [38]:
# pd.read_excel to open an excel file
help(pd.read_excel)
# In this function, we may need to specify a range of cells to open.
# skiprows=None, nrows=None

Help on function read_excel in module pandas.io.excel._base:

read_excel(io, sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, dtype: 'DtypeArg | None' = None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skipfooter=0, convert_float=None, mangle_dupe_cols=True, storage_options: 'StorageOptions' = None)
    Read an Excel file into a pandas DataFrame.
    
    Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
    read from a local filesystem or URL. Supports an option to read
    a single sheet or a list of sheets.
    
    Parameters
    ----------
    io : str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and 

In [ ]:
# Using Pandas to Read Large Excel Files in Python
# https://realpython.com/working-with-large-excel-files-in-pandas/

## Manipulate Pandas Dataframes

In [4]:
boxes = {'Color': ['Green','Green','Green','Blue','Blue','Red','Red','Red'],
         'Shape': ['Rectangle','Rectangle','Square','Rectangle','Square','Square','Square','Rectangle'],
         'Price': [10,15,5,5,10,15,15,5]
        }

df = pd.DataFrame(boxes, columns= ['Color','Shape','Price'])
df

Color      Shape  Price
0  Green  Rectangle     10
1  Green  Rectangle     15
2  Green     Square      5
3   Blue  Rectangle      5
4   Blue     Square     10
5    Red     Square     15
6    Red     Square     15
7    Red  Rectangle      5

In [6]:
# How to access specific column
# Method 1
df.Color # in R: df$Color

# If there's a space or other punctuation in the column name, use `Column Name`
# df.`Column Name`

# Method 2
df[["Color", "Shape"]] # Access multiple columns

Color      Shape
0  Green  Rectangle
1  Green  Rectangle
2  Green     Square
3   Blue  Rectangle
4   Blue     Square
5    Red     Square
6    Red     Square
7    Red  Rectangle

In [7]:
# How to add columns
# To add a column, you assign a column to a list of values Dataframe["Column Name"]=[list of values]
df['Fruit']=['Apple', 'Pear', 'Apple', 'Banana', 'Kiwi', 'Orange', 'Kiwi', 'Banana'] 
df

Color      Shape  Price   Fruit
0  Green  Rectangle     10   Apple
1  Green  Rectangle     15    Pear
2  Green     Square      5   Apple
3   Blue  Rectangle      5  Banana
4   Blue     Square     10    Kiwi
5    Red     Square     15  Orange
6    Red     Square     15    Kiwi
7    Red  Rectangle      5  Banana

In [8]:
# Remove a column
df=df.drop(["Fruit"], axis=1) # axis=1, not axis=0
df

Color      Shape  Price
0  Green  Rectangle     10
1  Green  Rectangle     15
2  Green     Square      5
3   Blue  Rectangle      5
4   Blue     Square     10
5    Red     Square     15
6    Red     Square     15
7    Red  Rectangle      5

In [10]:
# Relabel one column
df1=df.rename(columns={"Price":"Price1"})
df1

Color      Shape  Price1
0  Green  Rectangle      10
1  Green  Rectangle      15
2  Green     Square       5
3   Blue  Rectangle       5
4   Blue     Square      10
5    Red     Square      15
6    Red     Square      15
7    Red  Rectangle       5

In [11]:
# Relabel multiple columns
df2=df.rename(columns={"Color":"Color1", "Shape":"Shape1"})
df2

Color1     Shape1  Price
0  Green  Rectangle     10
1  Green  Rectangle     15
2  Green     Square      5
3   Blue  Rectangle      5
4   Blue     Square     10
5    Red     Square     15
6    Red     Square     15
7    Red  Rectangle      5

In [12]:
# Select observations which meet a particular condition; in R tidyverse: filter()
# The syntax is as follows: Dataframe.loc[Dataframe[`Column Name`] == condition]
df.loc[df['Color'] == 'Green']

# Same thing
df.loc[df.Color == 'Green']

Color      Shape  Price
0  Green  Rectangle     10
1  Green  Rectangle     15
2  Green     Square      5

## Select with loc vs iloc

In [19]:
# The loc and iloc functions can be used to access specific rows in a pandas dataframe.
# loc selects rows and columns with specific labels
# iloc selects rows and columns at specific integer positions

In [13]:
# Like accessing a column in a pandas dataframe, 
# but instead of having the string name of a column in the double square brackets, 
# it is a list of row indices/labels in the double square brackets
df.loc[[1, 2]] 

Color      Shape  Price
1  Green  Rectangle     15
2  Green     Square      5

In [14]:
# Unlike loc, we only need a single pair of square brackets
df.iloc[2:] 

Color      Shape  Price
2  Green     Square      5
3   Blue  Rectangle      5
4   Blue     Square     10
5    Red     Square     15
6    Red     Square     15
7    Red  Rectangle      5

In [16]:
# df.head(n) - show first n rows in Dataframe
df.head(n=3)

Color      Shape  Price
0  Green  Rectangle     10
1  Green  Rectangle     15
2  Green     Square      5

In [17]:
# Show count, mean, std, min, 25%, 50%, 75%, max of numerical variables
df.describe() 

Price
count   8.0000
mean   10.0000
std     4.6291
min     5.0000
25%     5.0000
50%    10.0000
75%    15.0000
max    15.0000

In [22]:
# Creates a crosstabulation of two categorical variables
# pd.crosstab(row_column, column_column, rownames=["rowlabel"], colnames=["collabel"])
pd.crosstab(df.Color, df.Shape, rownames=["Color1"], colnames=["Shape1"])

Shape1  Rectangle  Square
Color1                   
Blue            1       1
Green           2       1
Red             1       2

## Other useful pandas functions

In [23]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})
df

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [24]:
# Removes all rows from a Dataframe where values are null or NaN
# If you use axis=1, it would remove columns
df.dropna() 

name        toy       born
1  Batman  Batmobile 1940-04-25

In [25]:
# Check if values are null in a Dataframe
df.isna()
df.isnull()

name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

In [27]:
# Convert categorical columns into individual columns
pd.get_dummies(df["name"]) # In R, pivot_wider()

Alfred  Batman  Catwoman
0       1       0         0
1       0       1         0
2       0       0         1

In [28]:
# Drop rows where at least one element is missing
a=df.dropna()
a

name        toy       born
1  Batman  Batmobile 1940-04-25

In [26]:
# Drop columns where at one element is missing
b=df.dropna(axis=1)
b

name
0    Alfred
1    Batman
2  Catwoman

In [29]:
# Drop rows where all elements are missing
c=df.dropna(how="all")
c

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [30]:
df.isna()

name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

# AI in Medicine Presentation - Pandas

## Create a DataFrame from a list

In [4]:
data = np.random.randn(6, 4) # Create a random number (N(mean = 0, sd = 1)) table 
                             # with 6 rows and 4 columns

In [5]:
index_list = [11, 22, 33, 44, 55, 66] # Set row names
column_list = ["A", "B", "C", "D"] # Set column names

In [6]:
new_dataframe = pd.DataFrame(data, index = index_list, columns = column_list)
print(new_dataframe)

           A         B         C         D
11  0.771843 -0.706709  2.362205 -0.746312
22  1.723321 -0.092177 -1.077644  0.982769
33  0.436425  0.364907 -0.319067  0.359767
44 -1.096056  2.935010 -0.559510 -0.261696
55 -1.563474 -0.831034 -0.308743  0.218772
66 -0.811602  1.401129 -1.212568  0.021190


In [5]:
df1 = pd.DataFrame(data, columns = ["A", "B", "C", "D"])
print(df1)

          A         B         C         D
0 -0.411940 -1.254883 -0.459728  1.269386
1 -0.425805  0.951317 -0.862411  0.461015
2  0.104363  1.912879 -0.265856 -1.692084
3  0.298466  0.956408  0.010581  0.475522
4 -0.612216 -0.549455 -0.297885  0.522667
5  1.320094 -0.019938 -1.002583  0.085875


In [6]:
df2 = pd.DataFrame(data, index = index_list, columns = ["A", "B", "C", "D"])
print(df2)

           A         B         C         D
11 -0.411940 -1.254883 -0.459728  1.269386
22 -0.425805  0.951317 -0.862411  0.461015
33  0.104363  1.912879 -0.265856 -1.692084
44  0.298466  0.956408  0.010581  0.475522
55 -0.612216 -0.549455 -0.297885  0.522667
66  1.320094 -0.019938 -1.002583  0.085875


In [7]:
print(df2.head(2))

           A         B         C         D
11 -0.411940 -1.254883 -0.459728  1.269386
22 -0.425805  0.951317 -0.862411  0.461015


In [8]:
print(df2.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.045494  0.332721 -0.479647  0.187064
std    0.714985  1.156861  0.384560  0.998373
min   -0.612216 -1.254883 -1.002583 -1.692084
25%   -0.422339 -0.417076 -0.761740  0.179660
50%   -0.153788  0.465690 -0.378806  0.468269
75%    0.249940  0.955135 -0.273864  0.510881
max    1.320094  1.912879  0.010581  1.269386


## Create a DataFrame from CSV file

In [9]:
# Read CSV file
df = pd.read_csv("students.csv", delimiter = ",", header = 0) 
# Call read_csv function; 
# path: "students.csv" 
# header = 0 the first row as column names

print(df)
print(df.describe())

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     NaN
4    E   23     NaN   101.0
5    F   23   166.0   120.0
             age      height      weight
count   6.000000    5.000000    5.000000
mean   22.833333  173.400000  122.800000
std     0.752773    6.580274   22.862633
min    22.000000  166.000000  101.000000
25%    22.250000  167.000000  105.000000
50%    23.000000  176.000000  120.000000
75%    23.000000  177.000000  130.000000
max    24.000000  181.000000  158.000000


In [8]:
df1 = pd.read_csv("students.csv", delimiter = ",")
print(df1)
df2 = pd.read_csv("students.csv", delimiter = ",", header = 1) 
print(df2)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     NaN
4    E   23     NaN   101.0
5    F   23   166.0   120.0
   A  24    176    158
0  B  22  167.0  105.0
1  C  23  181.0  130.0
2  D  22  177.0    NaN
3  E  23    NaN  101.0
4  F  23  166.0  120.0


## Extract row names and column names

In [10]:
print(df.index.tolist())
print(df.columns.tolist())

[0, 1, 2, 3, 4, 5]
['name', 'age', 'height', 'weight']


In [11]:
# Load values from DataFrame as a numpy array
df_values = df.values
print(df_values)

[['A' 24 176.0 158.0]
 ['B' 22 167.0 105.0]
 ['C' 23 181.0 130.0]
 ['D' 22 177.0 nan]
 ['E' 23 nan 101.0]
 ['F' 23 166.0 120.0]]


## Sort a DataFrame

In [12]:
# Sort items by index
df1 = df.sort_index(ascending = False)
print(df1)

  name  age  height  weight
5    F   23   166.0   120.0
4    E   23     NaN   101.0
3    D   22   177.0     NaN
2    C   23   181.0   130.0
1    B   22   167.0   105.0
0    A   24   176.0   158.0


In [21]:
# Sort items by column "age"
df2 = df.sort_values(by = "age", ascending = False)
print(df2)

  name  age  height  weight
0    A   24   176.0   158.0
2    C   23   181.0   130.0
4    E   23     NaN   101.0
5    F   23   166.0   120.0
1    B   22   167.0   105.0
3    D   22   177.0     NaN


## Add a column to a DataFrame

In [22]:
df2["grade_1"] = [5, 4, 5, 4, 2, 3] # Add a score column into the existing DataFrame
print(df2)

  name  age  height  weight  grade_1
0    A   24   176.0   158.0        5
2    C   23   181.0   130.0        4
4    E   23     NaN   101.0        5
5    F   23   166.0   120.0        4
1    B   22   167.0   105.0        2
3    D   22   177.0     NaN        3


In [27]:
df2["grade_2"] = 5
print(df2)

    name  age  height  weight  grade_1  grade_2
0      A   24   176.0   158.0        5        5
2      C   23   181.0   130.0        4        5
4      E   23     NaN   101.0        5        5
5      F   23   166.0   120.0        4        5
1      B   22   167.0   105.0        2        5
3      D   22   177.0     NaN        3        5
7  Luke2   22   177.0   177.0        3        5


## Delete a column from a DataFrame

In [28]:
df_d = df2.drop(columns = ["name"]) # Delete the name column
print(df_d)

   age  height  weight  grade_1  grade_2
0   24   176.0   158.0        5        5
2   23   181.0   130.0        4        5
4   23     NaN   101.0        5        5
5   23   166.0   120.0        4        5
1   22   167.0   105.0        2        5
3   22   177.0     NaN        3        5
7   22   177.0   177.0        3        5


## Add a row to a DataFrame

In [25]:
# First method
df2.loc[7] = ["Luke2", 22, 177, 177, 3, 5] # Add a new row to the existing DataFrame
print(df2)

    name  age  height  weight  grade_1  grade_2
0      A   24   176.0   158.0        5        5
2      C   23   181.0   130.0        4        5
4      E   23     NaN   101.0        5        5
5      F   23   166.0   120.0        4        5
1      B   22   167.0   105.0        2        5
3      D   22   177.0     NaN        3        5
7  Luke2   22   177.0   177.0        3        5


In [16]:
# Second method
df2 = df2.append({"name":"Luke",
                  "age":20,
                  "height":177.0,
                  "weight":160,
                  "grade_1":5,
                  "grade_2":4},
                  ignore_index = True)
print(df2)

    name  age  height  weight  grade_1  grade_2
0      A   24   176.0   158.0        5        5
1      C   23   181.0   130.0        4        5
2      E   23     NaN   101.0        5        5
3      F   23   166.0   120.0        4        5
4      B   22   167.0   105.0        2        5
5      D   22   177.0     NaN        3        5
6  Luke2   22   177.0   177.0        3        5
7   Luke   20   177.0   160.0        5        4


## Delete a row from a DataFrame

In [33]:
df2
df_d = df2.drop(index = [7]) # Delete the seventh row (index = 7)
print(df_d)

  name  age  height  weight  grade_1  grade_2
0    A   24   176.0   158.0        5        5
2    C   23   181.0   130.0        4        5
4    E   23     NaN   101.0        5        5
5    F   23   166.0   120.0        4        5
1    B   22   167.0   105.0        2        5
3    D   22   177.0     NaN        3        5


## Selecting

In [20]:
# Select a column with the index
print(df["age"])

0    24
1    22
2    23
3    22
4    23
5    23
Name: age, dtype: int64


In [24]:
# Select a column without the index, as a numpy array
print(df["age"].values)

[24 22 23 22 23 23]


In [25]:
# select two columns
print(df.loc[:, ["age", "height"]])

   age  height
0   24   176.0
1   22   167.0
2   23   181.0
3   22   177.0
4   23     NaN
5   23   166.0


In [35]:
# Select the second row with the column name
row_2 = df.loc[1, :]
print(row_2)

name          B
age          22
height    167.0
weight    105.0
Name: 1, dtype: object


In [36]:
# Select the second row without the index, as a numpy array
row_2_value = df.loc[1, :].values
print(row_2_value)

['B' 22 167.0 105.0]


## Merge and concatenate a DataFrame

In [45]:
# Load data
df_new = pd.read_csv("student_grade.csv", header = 0)
print(df_new)

  name  math  python
0   AA     5       4
1    B     4       4
2    C     5       4
3    D     4       5
4   EE     3       5
5    F     5       3


## Merge a DataFrame with a database-style join

In [46]:
# Left merge
df_left_merge = pd.merge(df, df_new, how = "left", on = "name")
# how: type of merge {‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default ‘inner’
# left: use only keys from left frame, similar to a SQL left outer join; preserve key order
# on: column name to join on
# Reference: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

print(df_left_merge)

  name  age  height  weight  math  python
0    A   24   176.0   158.0   NaN     NaN
1    B   22   167.0   105.0   4.0     4.0
2    C   23   181.0   130.0   5.0     4.0
3    D   22   177.0     NaN   4.0     5.0
4    E   23     NaN   101.0   NaN     NaN
5    F   23   166.0   120.0   5.0     3.0


In [6]:
# Right merge
df_right_merge = pd.merge(df, df_new, how = "right", on = "name")
# right: use only keys from right frame, similar to a SQL right outer join; preserve key order

print(df_right_merge)

  name   age  height  weight  math  python
0   AA   NaN     NaN     NaN     5       4
1    B  22.0   167.0   105.0     4       4
2    C  23.0   181.0   130.0     5       4
3    D  22.0   177.0     NaN     4       5
4   EE   NaN     NaN     NaN     3       5
5    F  23.0   166.0   120.0     5       3


In [7]:
# Inner merge
df_inner_merge = pd.merge(df, df_new, how = "inner", on = "name")
# inner: use intersection of keys from both frames, similar to a SQL inner join; preserve the order of the left keys

print(df_inner_merge)

  name  age  height  weight  math  python
0    B   22   167.0   105.0     4       4
1    C   23   181.0   130.0     5       4
2    D   22   177.0     NaN     4       5
3    F   23   166.0   120.0     5       3


## Concatenate multiple DataFrames

In [39]:
# Read CSV files
df_1 = pd.read_csv("students_1.csv")
df_2 = pd.read_csv("students_2.csv")
print(df_1)
print(df_2)

  name  age  height  weight
0    H   24     176     158
1    I   22     167     105
  name  age  height  weight
0   KK   24     186     158


In [40]:
print(df)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     NaN
4    E   23     NaN   101.0
5    F   23   166.0   120.0


In [41]:
# Vertical direction combination
df_concat = pd.concat([df, df_1, df_2])
print(df_concat)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     NaN
4    E   23     NaN   101.0
5    F   23   166.0   120.0
0    H   24   176.0   158.0
1    I   22   167.0   105.0
0   KK   24   186.0   158.0


In [43]:
# Ignore old indices
df_concat_2 = pd.concat([df, df_1, df_2], ignore_index = True) # Default: ignore_index = False
print(df_concat_2)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     NaN
4    E   23     NaN   101.0
5    F   23   166.0   120.0
6    H   24   176.0   158.0
7    I   22   167.0   105.0
8   KK   24   186.0   158.0


## Address missing data

In [12]:
print(df)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     NaN
4    E   23     NaN   101.0
5    F   23   166.0   120.0


In [13]:
# Check missing values of each column
print(df.isnull().sum())

name      0
age       0
height    1
weight    1
dtype: int64


## Drop missing values - dropna

In [48]:
# Drop students who have any missing values
df_a = df.dropna(how = "any")
# axis{0 or ‘index’, 1 or ‘columns’}, default 0
# 0, or ‘index’ : Drop rows which contain missing values.
# 1, or ‘columns’ : Drop columns which contain missing value.

# how{‘any’, ‘all’}, default ‘any’
# ‘any’ : If any NA values are present, drop that row or column.
# ‘all’ : If all values are NA, drop that row or column.

# Reference: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

print(df_a)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
5    F   23   166.0   120.0


## Fill missing values - fillna

In [15]:
# Fill missing data by specific value
df_b = df.fillna(value = 5)

# Reference: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
    
print(df_b)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0     5.0
4    E   23     5.0   101.0
5    F   23   166.0   120.0


In [50]:
# Fill missing data by median value
df_c = df.fillna(df.median())
print(df_c)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0   120.0
4    E   23   176.0   101.0
5    F   23   166.0   120.0


/var/folders/s1/6460_yvs6ggdv14vc1dsk_r40000gn/T/ipykernel_5465/3037923389.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_c = df.fillna(df.median())


In [51]:
# Fill missing data by mean value
df_d = df.fillna(df.mean())
print(df_d)

  name  age  height  weight
0    A   24   176.0   158.0
1    B   22   167.0   105.0
2    C   23   181.0   130.0
3    D   22   177.0   122.8
4    E   23   173.4   101.0
5    F   23   166.0   120.0


/var/folders/s1/6460_yvs6ggdv14vc1dsk_r40000gn/T/ipykernel_5465/4105050071.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_d = df.fillna(df.mean())


## Impute missing values of specific columns using scikit-learn
### https://scikit-learn.org/stable/modules/classes.html#module-sklearn.impute

In [16]:
from sklearn.impute import SimpleImputer

In [17]:
# Impute missing value by mean, median, most_frequent, etc.
simple_imp = SimpleImputer(missing_values = np.nan, strategy = "mean")

In [18]:
simple_imp.fit(df[["age", "height", "weight"]])

SimpleImputer()

In [19]:
df_imputed_1 = df.copy()

In [22]:
df_imputed_1[["age", "height", "weight"]] = \
simple_imp.transform(df[["age", "height", "weight"]])

In [23]:
df_imputed_1

name   age  height  weight
0    A  24.0   176.0   158.0
1    B  22.0   167.0   105.0
2    C  23.0   181.0   130.0
3    D  22.0   177.0   122.8
4    E  23.0   173.4   101.0
5    F  23.0   166.0   120.0

In [27]:
# Impute missing values by values of the k nearest neighbors.
# sklearn version > 0.22
from sklearn.impute import KNNImputer

In [30]:
knn_imputer = KNNImputer(n_neighbors = 2)

In [31]:
knn_imputer.fit(df[["age", "height", "weight"]])

KNNImputer(n_neighbors=2)

In [35]:
df_imputed_2 = df.copy()

In [37]:
df_imputed_2[["age", "height", "weight"]] = \
knn_imputer.transform(df[["age", "height", "weight"]])

In [38]:
df_imputed_2

name   age  height  weight
0    A  24.0   176.0   158.0
1    B  22.0   167.0   105.0
2    C  23.0   181.0   130.0
3    D  22.0   177.0   129.5
4    E  23.0   172.0   101.0
5    F  23.0   166.0   120.0

## Data scaling

In [56]:
# Import packages
from sklearn import preprocessing
import numpy as np

In [54]:
data = np.arange(6, dtype = np.float32) # Create a 1D array; 6 = 0 - 5
print(data)

[0. 1. 2. 3. 4. 5.]
[[0 1 2]
 [3 4 5]]


In [43]:
print(data.shape, "ndim =", data.ndim)
print()

(6,) ndim = 1



In [44]:
data = data.reshape(6, 1) # Create a 2D array
print(data)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [45]:
print(data.shape, "ndim =", data.ndim)

(6, 1) ndim = 2


In [55]:
data = data.reshape(2, 3) # Create a 2D array
print(data)

data = np.array([[0, 1, 2], [3, 4, 5]]) # Create a matrix (2 rows x 3 columns)
print(data)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [47]:
print(data.shape, "ndim=", data.ndim)
print()

(2, 3) ndim= 2



In [57]:
# Standardize features by removing the mean and scaling to unit variance
# z = (x - u) / s
# Where u is the mean of the samples, and s is the standard deviation of the samples
print(data)

# Call StandardScaler function and assign it to the object scaler1
scaler1 = preprocessing.StandardScaler()

# Scale data
data_scaled = scaler1.fit_transform(data)

# Print output
print("StandardScaler:")
print(data_scaled)


print(scaler1.mean_) # Return mean value for each feature in the training set
print(scaler1.var_) # Return variance for each feature in the training set

# scaler1.fit_transform() == preprocessing.StandardScaler.fit_transform()

# Reference: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html 

[[0 1 2]
 [3 4 5]]
StandardScaler:
[[-1. -1. -1.]
 [ 1.  1.  1.]]
[1.5 2.5 3.5]
[2.25 2.25 2.25]


In [51]:
# Transform features by scaling each feature to a given range
scaler2 = preprocessing.MinMaxScaler()
print(data)
'''
X_std = (X - X.min(axis = 0)) / (X.max(axis = 0) - X.min(axis = 0))
X_scaled = X_std * (max - min) + min
'''
print("MinMaxScaler:")
print(scaler2.fit_transform(data))
print(scaler2.data_max_)
print(scaler2.data_min_)

[[0. 1. 2.]
 [3. 4. 5.]]
MinMaxScaler:
[[0. 0. 0.]
 [1. 1. 1.]]
[3. 4. 5.]
[0. 1. 2.]


In [52]:
# Normalize samples (rows) individually to unit norm
scaler3 = preprocessing.Normalizer(norm = "l2")
print(data)
print("Normalizer(L2):")
# [[0, 1/sqrt(5), 2/sqrt(5)], [3/sqrt(50), 4/sqrt(50), 5/sqrt(50)]] 
# 5 = 0^2 + 1^2 + 2^2, 50 = 3^2 + 4^2 + 5^2
print(scaler3.fit_transform(data))

[[0. 1. 2.]
 [3. 4. 5.]]
Normalizer(L2):
[[0.         0.4472136  0.8944272 ]
 [0.42426407 0.56568545 0.70710677]]


In [53]:
# Encode labels with value between 0 and n_classes - 1
le = preprocessing.LabelEncoder()
words = ["New York City", "Los Angeles", "Los Angeles", "Chicago", "Seattle"]
print("LabelEncoder:")
enc = le.fit_transform(words)
print(enc)
print(le.classes_)

LabelEncoder:
[2 1 1 0 3]
['Chicago' 'Los Angeles' 'New York City' 'Seattle']
